model: hf-mistral3
model_args:
  pretrained: # Will be injected by run script
  dtype: bfloat16 # Use bfloat8 for faster inference on compatible GPUs
  trust_remote_code: true

tasks:
  - none # Will be injected by run script

gen_kwargs:
  max_gen_toks: 35000
  # NOTE: this is needed to run HumanEval as temperature 0.0 causes evaluation to stop.
  # For tasks with do_sample=False, the temperature will be automatically set to 0.
  temperature: 0.001

batch_size: auto
device: cuda:0

apply_chat_template: true
confirm_run_unsafe_code: true

include_path: lm_eval_custom_polimi

output_path: data # Will be appended by run script
log_samples: true
