model: azure-openai-chat-completions
model_args:
  model: gpt-5-nano
  num_concurrent: 12
  max_retries: 3
  timeout: 180
  # NOTE: the tokenizer is only needed for RULER task
  tokenizer: openai-community/gpt2
  tokenized_requests: false
  # reasoning_effort: low

tasks:
  - none # Will be injected by run script

gen_kwargs:
  max_gen_toks: 35000

# use_cache: /workspaces/EngGPT-eval/.cache

apply_chat_template: true
confirm_run_unsafe_code: true

include_path: lm_eval_custom_polimi

output_path: data # Will be appended by run script
log_samples: true
