model: vllm
model_args:
  pretrained: # Will be injected by run script
  dtype: float16 # Use float16 for faster inference on compatible GPUs
  trust_remote_code: true
  enable_thinking: true
  think_end_token: </think>

gen_kwargs:
  max_gen_toks: 40000

include_path: lm_eval_custom_polimi

tasks:
  - none # Will be injected by run script

batch_size: auto
device: cuda:0

apply_chat_template: true
confirm_run_unsafe_code: true

output_path: data # Will be appended by run script
log_samples: true
